
package tango.gui.util;

import ij.IJ;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionListener;
import tango.gui.Core;
import tango.gui.PanelDisplayer;
/**
 *
 **
 * /**
 * Copyright (C) 2012 Jean Ollion
 *
 *
 *
 * This file is part of tango
 *
 * tango is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Jean Ollion
 */

public class ProcessingSequenceEditorLayout extends javax.swing.JPanel implements PanelDisplayer {
    public Dimension controlDim, editDim;
    Core core;
    public ProcessingSequenceEditorLayout(Core core)  {
        this.core=core;
        initComponents();
        editDim = new Dimension(this.editPanel.getPreferredSize().width-15, this.editPanel.getPreferredSize().height-15);
    }
    
    public void flush() {
        this.preFilterButtonPanel.removeAll();
        this.segButtonPanel.removeAll();
        this.postFilterButtonPanel.removeAll();
        this.preFilterList.removeAll();
        this.segList.removeAll();
        this.postFilterList.removeAll();
        
        IJ.log("avt flush: "+ this.preFilterList.getListSelectionListeners().length);
        for (ListSelectionListener lsl : this.preFilterList.getListSelectionListeners()) preFilterList.removeListSelectionListener(lsl);
        for (ListSelectionListener lsl : this.segList.getListSelectionListeners()) segList.removeListSelectionListener(lsl);
        for (ListSelectionListener lsl : this.postFilterList.getListSelectionListeners()) postFilterList.removeListSelectionListener(lsl);
        IJ.log("apres flush: "+ this.preFilterList.getListSelectionListeners().length);
        this.choicePanel.removeAll();
    }
    
    @Override
    public void showPanel(JPanel panel) {
        hidePanel();
        this.editScroll.setViewportView(panel);
        panel.setMinimumSize(editPanel.getMinimumSize());
        refreshDisplay();
        IJ.log("show panel");
    }

    @Override
    public void hidePanel() {
        this.editScroll.setViewportView(editPanel);
        refreshDisplay();
    }

    @Override
    public void refreshDisplay() {
        this.editScroll.repaint();
        this.editScroll.revalidate();
        core.refreshDisplay();
    }
    
    /*public void hideListPanels() {
        refreshListPanels();
    }*/
    
    /*public void showListPanels(JPanel prefilter, JPanel segmentation, JPanel postfilter) {
        hideListPanels();
        prefilter.setMinimumSize(preFilterPanel.getMinimumSize());
        this.preFilterScroll.setViewportView(prefilter);
        segmentation.setMinimumSize(segmentationPanel.getMinimumSize());
        this.segmentationScoll.setViewportView(segmentation);
        postfilter.setMinimumSize(postFilterPanel.getMinimumSize());
        this.postFilterScroll.setViewportView(postfilter);
        refreshListPanels();
    }*/
    
    public void refreshListPanels() {
        /*this.preFilterScroll.repaint();
        this.preFilterScroll.revalidate();
        this.segmentationScoll.repaint();
        this.segmentationScoll.revalidate();
        this.postFilterScroll.repaint();
        this.postFilterScroll.revalidate();*/
        preFilterList.updateUI();
        segList.updateUI();
        postFilterList.updateUI();
        core.refreshDisplay();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editScroll = new javax.swing.JScrollPane();
        editPanel = new javax.swing.JPanel();
        preFilterPanel = new javax.swing.JPanel();
        preFilterButtonPanel = new javax.swing.JPanel();
        preFilterJSP = new javax.swing.JScrollPane();
        preFilterList = new javax.swing.JList();
        segPanel = new javax.swing.JPanel();
        segButtonPanel = new javax.swing.JPanel();
        segJSP = new javax.swing.JScrollPane();
        segList = new javax.swing.JList();
        postFilterPanel = new javax.swing.JPanel();
        postFilterButtonPanel = new javax.swing.JPanel();
        postFilterJSP = new javax.swing.JScrollPane();
        postFilterList = new javax.swing.JList();
        choicePanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(738, 600));
        setMinimumSize(new java.awt.Dimension(738, 600));
        setPreferredSize(new java.awt.Dimension(738, 600));

        editPanel.setMinimumSize(new java.awt.Dimension(430, 574));
        editPanel.setPreferredSize(new java.awt.Dimension(430, 574));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        editScroll.setViewportView(editPanel);

        preFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Pre-Filters")));

        preFilterButtonPanel.setLayout(new javax.swing.BoxLayout(preFilterButtonPanel, javax.swing.BoxLayout.LINE_AXIS));

        preFilterList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        preFilterJSP.setViewportView(preFilterList);

        javax.swing.GroupLayout preFilterPanelLayout = new javax.swing.GroupLayout(preFilterPanel);
        preFilterPanel.setLayout(preFilterPanelLayout);
        preFilterPanelLayout.setHorizontalGroup(
            preFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preFilterPanelLayout.createSequentialGroup()
                .addGroup(preFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(preFilterJSP)
                    .addComponent(preFilterButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        preFilterPanelLayout.setVerticalGroup(
            preFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preFilterPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(preFilterButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(preFilterJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        );

        segPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Segmentation"));

        segButtonPanel.setLayout(new javax.swing.BoxLayout(segButtonPanel, javax.swing.BoxLayout.LINE_AXIS));

        segList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        segJSP.setViewportView(segList);

        javax.swing.GroupLayout segPanelLayout = new javax.swing.GroupLayout(segPanel);
        segPanel.setLayout(segPanelLayout);
        segPanelLayout.setHorizontalGroup(
            segPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segPanelLayout.createSequentialGroup()
                .addGroup(segPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(segButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(segJSP))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        segPanelLayout.setVerticalGroup(
            segPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(segButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(segJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        postFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Post-Filters"));

        postFilterButtonPanel.setLayout(new javax.swing.BoxLayout(postFilterButtonPanel, javax.swing.BoxLayout.LINE_AXIS));

        postFilterList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        postFilterJSP.setViewportView(postFilterList);

        javax.swing.GroupLayout postFilterPanelLayout = new javax.swing.GroupLayout(postFilterPanel);
        postFilterPanel.setLayout(postFilterPanelLayout);
        postFilterPanelLayout.setHorizontalGroup(
            postFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postFilterPanelLayout.createSequentialGroup()
                .addGroup(postFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(postFilterJSP)
                    .addComponent(postFilterButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        postFilterPanelLayout.setVerticalGroup(
            postFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postFilterPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(postFilterButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(postFilterJSP))
        );

        choicePanel.setLayout(new javax.swing.BoxLayout(choicePanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(segPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(postFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel choicePanel;
    public javax.swing.JPanel editPanel;
    private javax.swing.JScrollPane editScroll;
    public javax.swing.JPanel postFilterButtonPanel;
    private javax.swing.JScrollPane postFilterJSP;
    public javax.swing.JList postFilterList;
    public javax.swing.JPanel postFilterPanel;
    public javax.swing.JPanel preFilterButtonPanel;
    private javax.swing.JScrollPane preFilterJSP;
    public javax.swing.JList preFilterList;
    public javax.swing.JPanel preFilterPanel;
    public javax.swing.JPanel segButtonPanel;
    private javax.swing.JScrollPane segJSP;
    public javax.swing.JList segList;
    public javax.swing.JPanel segPanel;
    // End of variables declaration//GEN-END:variables


    
}
